#!/usr/bin/env bash 

if [ "${SNAP_ARCH}" == "amd64" ]; then
  ARCH="x86_64-linux-gnu"
  OBS="64bit"
elif [ "${SNAP_ARCH}" == "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "${SNAP_ARCH}" == "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="${SNAP_ARCH}-linux-gnu"
  OBS="32bit"
fi

VENDOR=$(glxinfo | grep "OpenGL vendor")

if [[ $VENDOR == *"Intel"* ]]; then
  export VDPAU_DRIVER_PATH="${SNAP}/usr/lib/$ARCH/dri"
  export LIBVA_DRIVERS_PATH="${SNAP}/usr/lib/$ARCH/dri"
  $SNAP/usr/bin/vainfo
fi

if [[ $VENDOR == *"NVIDIA"* ]]; then
  export VDPAU_DRIVER_PATH="/var/lib/snapd/lib/gl/vdpau"
elif [[ $VENDOR == *"X.Org"* ]]; then
  export VDPAU_DRIVER_PATH="/usr/lib/${ARCH}/vdpau/"
fi

# Pulseaudio export
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SNAP/usr/lib/$ARCH/pulseaudio

# Make PulseAudio socket available inside the snap-specific $XDG_RUNTIME_DIR
if [ -n "$XDG_RUNTIME_DIR" ]; then
    pulsenative="pulse/native"
    pulseaudio_sockpath="$XDG_RUNTIME_DIR/../$pulsenative"
    if [ -S "$pulseaudio_sockpath" ]; then
        export PULSE_SERVER="unix:${pulseaudio_sockpath}"
    fi
fi

echo $PATH

REALHOME=`getent passwd $UID | cut -d ':' -f 6`
if [ -d "$XDG_CONFIG_HOME/obs-studio" ]; then
  if [ -e "$REALHOME/.config/obs-studio" ]; then
    echo "Cannot migrate your configuration files to $REALHOME/config/obs-studio."
    echo "Your OBS configuration is stored in $XDG_CONFIG_HOME/obs-studio"
    echo "Please migrate and merge these files with $REALHOME/config/obs-studio,"
    echo "and then delete $XDG_CONFIG_HOME/obs-studio..."
  else
    echo "Migrating OBS configuration files from $XDG_CONFIG_HOME/obs-studio"
    echo "to $REALHOME/.config/obs-studio..."
    mv "$XDG_CONFIG_HOME/obs-studio" "$REALHOME/.config/obs-studio"
    ln -s "$REALHOME/.config/obs-studio" "$XDG_CONFIG_HOME/obs-studio"
    echo "DONE. You may now find your configuration in $REALHOME/.config/obs-studio."
  fi
else
  if [ ! -e "$XDG_CONFIG_HOME/obs-studio" ]; then
    ln -s "$REALHOME/.config/obs-studio" "$XDG_CONFIG_HOME/obs-studio"
  fi
  echo "Your OBS configuration files are stored in $REALHOME/.config/obs-studio."
fi

cd $SNAP/usr/bin/$OBS

exec ./obs "$@"