#!/usr/bin/env bash

# Export the Vulkan ICD filename paths
#  - There is no Intel ICD for ARM
if [ "$SNAP_ARCH" = "amd64" ]; then
  export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json"
elif [ "$SNAP_ARCH" = "i386" ]; then
  export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.i686.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.i686.json"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.armv7l.json"
elif [ "$SNAP_ARCH" = "arm64" ]; then
  export VK_ICD_FILENAMES="/var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.aarch64.json"
fi

# If the current session is Wayland then use EGL
if [ "${XDG_SESSION_TYPE}" == "wayland" ] && [[ ${WAYLAND_DISPLAY} == *"wayland"* ]]; then
  export QT_QPA_PLATFORM="wayland"
elif [ "${XDG_SESSION_TYPE}" == "x11" ]; then
  export QT_QPA_PLATFORM="xcb"
fi

# The gnome extension sets XDG_CONFIG_HOME=$SNAP_USER_DATA/.config (revision-specific)
# in the command-chain, which OBS's os_get_config_path checks before $HOME/.config.
# Override it here so the OBS settings survive snap refreshes
export XDG_CONFIG_HOME="$SNAP_USER_COMMON/.config"

unset SESSION_MANAGER

# obs is run with --multi because it tries to bind a UNIX socket as lock
# file but it's not namespaced as would be necessary for a snap in strict
# confinement, without --multi it shows a warning at every startup that obs
# is already running
exec obs --multi  "${@}"
