#!/usr/bin/env bash

WRAPPER=$(basename $0)

if [ "${SNAP_ARCH}" == "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "${SNAP_ARCH}" == "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "${SNAP_ARCH}" == "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="${SNAP_ARCH}-linux-gnu"
fi

VENDOR=$(glxinfo | grep "OpenGL vendor")

if [[ $VENDOR == *"Intel"* ]]; then
  export VDPAU_DRIVER_PATH="${SNAP}/usr/lib/$ARCH/dri"
  export LIBVA_DRIVERS_PATH="${SNAP}/usr/lib/$ARCH/dri"
fi

if [[ $VENDOR == *"NVIDIA"* ]]; then
  export VDPAU_DRIVER_PATH="/var/lib/snapd/lib/gl/vdpau"
elif [[ $VENDOR == *"X.Org"* ]]; then
  export VDPAU_DRIVER_PATH="/usr/lib/${ARCH}/vdpau/"
fi

# Pulseaudio export
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SNAP/usr/lib/$ARCH/pulseaudio

# Make PulseAudio socket available inside the snap-specific $XDG_RUNTIME_DIR
if [ -n "$XDG_RUNTIME_DIR" ]; then
    pulsenative="pulse/native"
    pulseaudio_sockpath="$XDG_RUNTIME_DIR/../$pulsenative"
    if [ -S "$pulseaudio_sockpath" ]; then
        export PULSE_SERVER="unix:${pulseaudio_sockpath}"
    fi
fi

exec $SNAP/usr/bin/$WRAPPER "$@"