#!/bin/bash -x

case "$SNAP_ARCH" in
    *86)
    ARCH="i386-linux-gnu"
    OBS="32bit"
    ;;
    *64)
    ARCH="x86_64-linux-gnu"
    OBS="64bit"
    ;;
    *)
    ARCH="$SNAP_ARCH-linux-gnu"
    ;;
esac

cd $SNAP/usr/bin/$OBS

exec ./obs "$@"