name: obs-studio
summary: Live streaming and video recording software
description: Free and open source software for video capturing, recording, and live
  streaming.
version: "31.1.0"
base: core24
grade: stable
confinement: strict
license: GPL-2.0
compression: lzo

platforms:
  amd64:

package-repositories:
  - type: apt
    ppa: obsproject/obs-studio
    priority: prefer
    key-id: BC7345F522079769F5BBE987EFC71127F425E228
  - type: apt
    ppa: kobuk-team/intel-graphics
    priority: prefer
    key-id: 0C0E6AF955CE463C03FC51574D098D70AFBE5E1F

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

parts:
  launcher:
    plugin: dump
    source: snap/local

  obs-studio:
    plugin: nil
    stage-packages:
      - obs-studio
      - libvlc5
      - vlc-plugin-base

  intel-graphics:
    plugin: nil
    stage-packages:
      - vainfo
      - intel-media-va-driver-non-free
      - libvpl2
      - libvpl-dev
      - libva-drm2
      - libva-glx2
      - libva-wayland2
      - libva-x11-2
      - libva-dev
      - libmfx1
      - libmfx-gen1
      - libmfx-gen-dev
      - libigdgmm12
      - libigdgmm-dev

apps:
  obs-studio:
    command: obs-wrapper
    extensions: [gnome]
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins/platforms
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/obs-plugins:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/obs-scripting:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LIBVA_DRIVERS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$LIBVA_DRIVERS_PATH
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - avahi-control
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - hardware-observe
      - jack1
      - joystick
      - kernel-module-observe
      - network
      - network-bind
      - opengl
      - password-manager-service
      - process-control
      - pulseaudio
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - screencast-legacy
      - system-observe
      - unity7
      - upower-observe
      - wayland
      - x11
