name: obs-studio
summary: OBS - Free and open source software for live streaming and screen recording
description: |
  OBS Studio is software designed for capturing, compositing, encoding, recording, 
  and streaming video content, efficiently.
  It's distributed under the GNU General Public License v2 - see the accompanying COPYING file for more details.
adopt-info: obs

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  
# We should migrate to using the official folder for obs-studio config  
#plugs:
#  obs-config-dir:
#    interface: personal-files
#    write: [$HOME/.config/obs-studio]

apps:
  ffmpeg:
    command: bin/ffmpeg
    environment:
      # Tell libGL where to find the drivers
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
      # Mesa Libs for OpenGL support
      # Workaround in snapd for proprietary nVidia drivers mounts the drivers in
      # /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
      # Without that OpenGL using apps do not work with the nVidia drivers.
      # Ref.: https://bugs.launchpad.net/snappy/+bug/1588192
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-egl:$LIBGL_DRIVERS_PATH:/var/lib/snapd/lib/gl
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - audio-playback
      - audio-record
      - removable-media
      - wayland
      - x11
  ffprobe:
    command: bin/ffprobe
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - audio-playback
      - audio-record
      - removable-media
      - wayland
      - x11
  ffplay:
    command: bin/ffplay
    plugs:
      - alsa
      - camera
      - desktop
      - hardware-observe
      - home
      - network-bind
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - audio-playback
      - audio-record
      - removable-media
      - wayland
      - x11
  obs-studio:
    command: desktop-launch $SNAP/bin/launcher
    command-chain:
      - sem-open-preload-launch
    environment:
      # Tell libGL where to find the drivers
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
      # Mesa Libs for OpenGL support
      # Workaround in snapd for proprietary nVidia drivers mounts the drivers in
      # /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
      # Without that OpenGL using apps do not work with the nVidia drivers.
      # Ref.: https://bugs.launchpad.net/snappy/+bug/1588192
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-egl:$LIBGL_DRIVERS_PATH:/var/lib/snapd/lib/gl:$SNAP_USER_DATA/.config/obs-studio/plugins/libs
    plugs:
      - browser-support
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - opengl
      - pulseaudio
      - audio-playback
      - audio-record
      - x11
      - unity7
      - camera
      - home
      - removable-media
      - wayland
      - jack1

parts:
  sem-open-preload:
    source: https://github.com/sergiusens/sem-open-preload.git
    plugin: make
  desktop-qt5:
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      make-parameters:
        - FLAVOR=qt5
      plugin: make
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgtk2.0-0
        - libgdk-pixbuf2.0-0
        - libqt5svg5
        - locales-all
        - qtwayland5
        - xdg-user-dirs
  obs:
    plugin: cmake 
    after: [desktop-qt5]
    configflags: ["-DUNIX_STRUCTURE=0", "-DCMAKE_INSTALL_PREFIX=/usr", "-DBUILD_BROWSER=ON", "-DCEF_ROOT_DIR=$SNAPCRAFT_PART_INSTALL/cef_binary_3770_linux64"]
    source: https://github.com/obsproject/obs-studio.git
    override-pull: |
      snapcraftctl pull
      set -x
      ARCHITECTURE=$(dpkg --print-architecture)
      if [ "${ARCHITECTURE}" = "amd64" ]; then
        SUFFIX="linux64"
      elif [ "${ARCHITECTURE}" = "i386" ]; then
        SUFFIX="linux32"
      fi
      last_committed_tag="$(git -C ../src tag | grep -v rc| sort -V | tail -n 1)"
      last_released_tag="$(snap info obs-studio | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      wget --quiet https://cdn-fastly.obsproject.com/downloads/cef_binary_3770_$SUFFIX.tar.bz2 -O $SNAPCRAFT_PART_INSTALL/cef.tar.bz2
      tar jxvf $SNAPCRAFT_PART_INSTALL/cef.tar.bz2 -C $SNAPCRAFT_PART_INSTALL/
      rm $SNAPCRAFT_PART_INSTALL/cef.tar.bz2
      snapcraftctl set-version "$(git describe --tags)"
    build-packages:
      - bzip2
      - wget
      - libx11-dev           # From the docs
      - libgl1-mesa-dev 
      - libvlc-dev
      - libpulse-dev
      - libxcomposite-dev
      - libxinerama-dev
      - libv4l-dev
      - libudev-dev
      - libfreetype6-dev
      - libfontconfig-dev
      - libluajit-5.1-dev
      - python3-dev
      - swig
      - pkg-config
      - qtbase5-dev
      - libqt5x11extras5-dev
      - libqt5svg5-dev
      - libx264-dev
      - libxcb-xinerama0-dev
      - libxcb-shm0-dev
      - libcurl4-openssl-dev
      - libavcodec-dev       # if not building ffmpeg
      - libavfilter-dev
      - libavdevice-dev
      - libfdk-aac-dev
      - libspeexdsp-dev      # cmake complains if missing
      - libmbedtls-dev
      - libjack-dev
      - libnss3
      - libnspr4
    stage-packages:
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libxtst6
      - libnss3
      - libnspr4
      - libvlc5
      - libslang2
      - libxcomposite1
      - libpython3.6
      - libzvbi0
      - libzmq5
      - libxvidcore4
      - libxv1
      - libxcb-xinerama0
      - libx265-146
      - libx264-152
      - libwebp6
      - libwavpack1
      #- libvpx3
      - libvorbisenc2
      - libvorbis0a
      - libva2
      - libv4lconvert0
      - libv4l-0
      - libtwolame0
      - libtheora0
      - libtbb2
      #- libswscale-ffmpeg3
      #- libswresample-ffmpeg1
      - libssh-gcrypt-4
      - libspeexdsp1
      - libspeex1
      - libsoxr0
      - libsodium23
      - libsndfile1
      - libsnappy1v5
      - libshine3
      - libsdl1.2debian
      #- libschroedinger-1.0-0
      - librtmp1
      - libraw1394-11
      - libqt5x11extras5
      - libpulse0
      #- libpostproc-ffmpeg53
      - liborc-0.4-0
      - libopus0
      #- libopenjpeg5
      - libopencv-imgproc3.2
      - libopencv-core3.2
      - libopenal1
      - libogg0
      - libmp3lame0
      - libmodplug1
      - libiec61883-0
      - libgsm1
      - libgomp1
      - libgme0
      - libglu1-mesa
      - libfribidi0
      - libflite1
      - libflac8
      #- libfdk-aac0
      - libdc1394-22
      - libcurl4
      - libcrystalhd3
      #- libcdio-paranoia1
      - libcdio-cdda2
      - libcdio17
      - libcaca0
      - libbs2b0
      - libbluray2
      #- libavutil-ffmpeg54
      #- libavresample-ffmpeg2
      #- libavformat-ffmpeg56
      #- libavfilter-ffmpeg5
      #- libavdevice-ffmpeg56
      #- libavcodec-ffmpeg-extra56
      - libavc1394-0
      - libasyncns0
      - libass9
      - libasound2
      - libdb5.3
      - libluajit-5.1-2
      - libpython3.7
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libmbedcrypto1
      - libmbedtls10
      - libmbedx509-0
      - libqt5xml5
      - freeglut3
      - jackd1
      - on amd64: 
        - libnuma1
      - on i386: 
        - libnuma1
      - on arm64: 
        - libnuma1
  nv-codec-headers:
    plugin: make
    source: https://github.com/FFmpeg/nv-codec-headers/releases/download/n9.1.23.1/nv-codec-headers-9.1.23.1.tar.gz
    override-build: |
      make install PREFIX=/usr
    build-packages:
      - pkg-config

  fdk-aac:
    plugin: autotools
    source: https://github.com/mstorsjo/fdk-aac/archive/v2.0.0.tar.gz
    build-packages:
      - g++
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - usr/lib
      - usr/lib/pkgconfig
      - usr/include

  ffmpeg:
    plugin: autotools
    source: https://github.com/FFmpeg/FFmpeg.git
    build-environment: 
      - PATH: "/usr/lib/ccache:$PATH"
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag -l | grep -v v | sort -rV | head -n1)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/n//')"
      last_released_tag="$(snap info ffmpeg | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$last_committed_tag_ver"
    override-build: |
       snapcraftctl build
       ccache -s
    build-packages:
      - ccache
      - libass-dev
      - libbz2-dev
      - libdrm-dev
      - libgnutls28-dev
      - liblzma-dev
      - libmp3lame-dev
      - libomxil-bellagio-dev
      - libopenal-dev
      - libopencore-amrnb-dev
      - libopencore-amrwb-dev
      - libopus-dev
      - libpulse-dev
      - libsctp-dev
      - libsdl2-dev
      - libspeex-dev
      - libtheora-dev
      - libtwolame-dev
      - libva-dev
      - libv4l-dev
      - libvdpau-dev
      - libvorbis-dev
      - libvpx-dev
      - libx264-dev
      - libx265-dev
      - libxcb-shape0-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - libxv-dev
      - libxvidcore-dev
      - ocl-icd-opencl-dev
      - opencl-headers
      - pkg-config
      - yasm
      - on amd64:
        - libcrystalhd-dev
      - on i386:
        - libcrystalhd-dev
    stage-packages:
      - i965-va-driver
      - libass9
      - libdrm2
      - libgnutls30
      - libmp3lame0
      - libopenal1
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopus0
      - libpulse0
      - libsdl2-2.0-0
      - libspeex1
      - libtheora0
      - libtwolame0
      - libv4l-0
      - libv4l2rds0
      - libva-drm2
      - libva-glx2
      - libva-wayland2
      - libvdpau-va-gl1
      - libvorbis0a
      - libvorbisenc2
      - libvpx5
      - libx264-152
      - libx265-146
      - libx11-6
      - libxau6
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxv1
      - libxvidcore4
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - ocl-icd-libopencl1
      - on amd64:
        - libcrystalhd3
      - on i386:
        - libcrystalhd3
    configflags:
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-avisynth
      - --enable-cuda
      - --enable-cuvid
      - --enable-libdrm
      - --enable-ffplay
      - --enable-gnutls
      - --enable-gpl
      - --enable-libass
      - --enable-libfdk-aac
      - --enable-libfontconfig
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libopencore_amrnb
      - --enable-libopencore_amrwb
      - --enable-libopus
      - --enable-libpulse
      - --enable-sdl2
      - --enable-libspeex
      - --enable-libtheora
      - --enable-libtwolame
      - --enable-libv4l2
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libx264
      - --enable-libx265
      - --enable-libxcb
      - --enable-libxvid
      - --enable-nonfree
      - --enable-nvenc
      - --enable-omx
      - --enable-openal
      - --enable-opencl
      - --enable-runtime-cpudetect
      - --enable-shared
      - --enable-vaapi
      - --enable-vdpau
      - --enable-version3
      - --enable-xlib
    after:
      - nv-codec-headers
      - fdk-aac
    prime:
      - usr/bin
      - usr/lib
      - usr/lib/pkgconfig
      - usr/include
      - -usr/share/doc
      - -usr/share/man

  ffmpeg-wrapper:
    plugin: dump
    source: snap/local/
    stage-packages:
      - mesa-utils
      - vainfo
    organize:
      'ffplay': bin/
      'ffmpeg': bin/
      'ffprobe': bin/
      'wrapper': bin/
      'launcher': bin/
    after:
      - ffmpeg
