name: obs-studio
summary: Live streaming and video recording software
description: Free and open source software for video capturing, recording, and live
  streaming.
version: "31.0.3"
base: core24
grade: stable
confinement: strict
license: GPL-2.0
compression: lzo

platforms:
  amd64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio

parts:
  launcher:
    plugin: dump
    source: snap/local
  obs-studio:
    source: https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu/pool/main/o/obs-studio/obs-studio_31.0.3-0obsproject1~noble_amd64.deb
    build-attributes:
      - enable-patchelf
    source-type: deb
    plugin: dump
  deps:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libavfilter9
      - libswresample4
      - libpostproc57
      - liblapack3
      - libblas3
      - libvlc5
      - vlc-plugin-base
      - stterm
      - libfdk-aac2
      - libvlc5
      - qt6-qpa-plugins
      - librsvg2-common
      - libgdk-pixbuf-2.0-0
      - libcurl4
      - pulseaudio
      - qt6-image-formats-plugins
      - qt6-wayland
      - python3
      - python3.12
      - libavcodec60
      - libavdevice60
      - libavformat60
      - libavutil58
      - libc6
      - libfontconfig1
      - libfreetype6
      - libgcc-s1
      - libglx0
      - libjansson4
      - libluajit-5.1-2
      - libmbedcrypto7t64
      - libmbedtls14t64
      - libmbedx509-1t64
      - libopengl0
      - libpci3
      - libpulse0
      - libpython3.12t64
      - libqrcodegencpp1
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6svg6
      - libqt6widgets6t64
      - libqt6xml6t64
      - librist4
      - libspeexdsp1
      - libsrt1.5-openssl
      - libstdc++6
      - libswscale7
      - libudev1
      - libv4l-0t64
      - libva-drm2
      - libva2
      - libx11-6
      - libx264-164
      - libxcb-composite0
      - libxcb-randr0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb1
      - libxkbcommon0

apps:
  obs-studio:
    command: obs-wrapper
    extensions: [gnome]
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins/platforms
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/obs-plugins:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/obs-scripting:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - avahi-control
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - hardware-observe
      - jack1
      - joystick
      - kernel-module-observe
      - network
      - network-bind
      - opengl
      - password-manager-service
      - process-control
      - pulseaudio
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - screencast-legacy
      - system-observe
      - unity7
      - upower-observe
      - wayland
      - x11
