name: obs-studio
summary: OBS - Free and open source software for live streaming and screen recording
description: |
  OBS Studio is software designed for capturing, compositing, encoding, recording, 
  and streaming video content, efficiently.
  It's distributed under the GNU General Public License v2 - see the accompanying COPYING file for more details.
adopt-info: obs

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
  
apps:
  obs-studio:
    command: desktop-launch $SNAP/launcher
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - opengl
      - pulseaudio
      - x11
      - unity7
      - camera
      - home
      - removable-media

parts:
  scripts:
    plugin: dump
    source: ./snap/scripts
  obs:
    plugin: cmake 
    after: [desktop-qt5]
    configflags: ["-DUNIX_STRUCTURE=0", "-DCMAKE_INSTALL_PREFIX=/usr"]
    source: https://github.com/obsproject/obs-studio.git
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git tag | sort -V | tail -n 1)"
      last_released_tag="$(snap info obs-studio | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags)"
    build-packages:
      - libx11-dev           # From the docs
      - libgl1-mesa-dev 
      - libvlc-dev
      - libpulse-dev
      - libxcomposite-dev
      - libxinerama-dev
      - libv4l-dev
      - libudev-dev
      - libfreetype6-dev
      - libfontconfig-dev
      - libluajit-5.1-dev
      - python3-dev
      - swig
      - pkg-config
      - qtbase5-dev
      - libqt5x11extras5-dev
      - libx264-dev
      - libxcb-xinerama0-dev
      - libxcb-shm0-dev
      - libjack-jackd2-dev
      - libcurl4-openssl-dev
      - libavcodec-dev       # if not building ffmpeg
      - libavfilter-dev
      - libavdevice-dev
      - libfdk-aac-dev
      - libspeexdsp-dev      # cmake complains if missing
    stage-packages:
      - libzvbi0
      - libzmq5
      - libxvidcore4
      - libxv1
      - libxcb-xinerama0
      - libx265-79
      - libx264-148
      - libwebp5
      - libwavpack1
      - libvpx3
      - libvorbisenc2
      - libvorbis0a
      - libva1
      - libv4lconvert0
      - libv4l-0
      - libtwolame0
      - libtheora0
      - libtbb2
      - libswscale-ffmpeg3
      - libswresample-ffmpeg1
      - libssh-gcrypt-4
      - libspeexdsp1
      - libspeex1
      - libsoxr0
      - libsodium18
      - libsndfile1
      - libsnappy1v5
      - libshine3
      - libsdl1.2debian
      - libschroedinger-1.0-0
      - librtmp1
      - libraw1394-11
      - libqt5x11extras5
      - libpulse0
      - libpostproc-ffmpeg53
      - liborc-0.4-0
      - libopus0
      - libopenjpeg5
      - libopencv-imgproc2.4v5
      - libopencv-core2.4v5
      - libopenal1
      - libogg0
      - libmp3lame0
      - libmodplug1
      - libjack-jackd2-0
      - libiec61883-0
      - libgsm1
      - libgomp1
      - libgme0
      - libglu1-mesa
      - libfribidi0
      - libflite1
      - libflac8
      - libfdk-aac0
      - libdc1394-22
      - libcurl3
      - libcrystalhd3
      - libcdio-paranoia1
      - libcdio-cdda1
      - libcdio13
      - libcaca0
      - libbs2b0
      - libbluray1
      - libavutil-ffmpeg54
      - libavresample-ffmpeg2
      - libavformat-ffmpeg56
      - libavfilter-ffmpeg5
      - libavdevice-ffmpeg56
      - libavcodec-ffmpeg-extra56
      - libavc1394-0
      - libasyncns0
      - libass5
      - libasound2
      - libdb5.3
      - libluajit-5.1-2
      - libpython3.5
      - on amd64: 
        - libnuma1
      - on i386: 
        - libnuma1
      - on arm64: 
        - libnuma1
