name: obs-studio
summary: Live streaming and video recording software
description: Free and open source software for video capturing, recording, and live
  streaming.
version: "31.1.1"
base: core24
grade: stable
confinement: strict
license: GPL-2.0
compression: lzo

platforms:
  amd64:

package-repositories:
  - type: apt
    ppa: obsproject/obs-studio
    priority: prefer
    key-id: BC7345F522079769F5BBE987EFC71127F425E228
  - type: apt
    ppa: kobuk-team/intel-graphics
    priority: prefer
    key-id: 0C0E6AF955CE463C03FC51574D098D70AFBE5E1F

plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    target: $SNAP/openvino

components:
  openvino-plugins:
    type: standard
    summary: OpenVINO AI plugins
    description: OpenVINO based plugins that add AI features to OBS Studio

parts:
  launcher:
    plugin: dump
    source: snap/local

  obs-studio:
    plugin: nil
    stage-packages:
      - obs-studio
      - libvlc5
      - vlc-plugin-base
  openvino-plugins:
    source: https://github.com/intel/openvino-plugins-for-obs-studio.git
    source-type: git
    plugin: dump
    after: [ 'obs-studio' ]
    build-environment:
      - OpenVINO_DIR: /snap/openvino-toolkit-2404/current/usr/lib/x86_64-linux-gnu/cmake/openvino2025.1.0/
    build-packages:
      - libopencv-dev
      - cmake
    build-snaps:
      - openvino-toolkit-2404
    override-build: |
      set -eux
      cd $CRAFT_PART_BUILD
      cmake .
      CORES="$(nproc)"
      make -j$CORES
      cp $CRAFT_PART_BUILD/intel64/Release/lib/*.so $CRAFT_PART_INSTALL/
      mkdir $CRAFT_PART_INSTALL/{obs-smart-framing-ov,obs-face-mesh-ov,obs-backgroundconcealment-ov}
      cp -R openvino-models/ $CRAFT_PART_INSTALL/
    organize:
      libobs-backgroundconcealment-ov.so: (component/openvino-plugins)
      libobs-face-mesh-ov.so: (component/openvino-plugins)
      libobs-smart-framing-ov.so: (component/openvino-plugins)
      obs-smart-framing-ov: (component/openvino-plugins)/obs-smart-framing-ov
      obs-face-mesh-ov: (component/openvino-plugins)/obs-face-mesh-ov
      obs-backgroundconcealment-ov: (component/openvino-plugins)/obs-backgroundconcealment-ov
      openvino-models: (component/openvino-plugins)/openvino-models
    stage-packages:
      - libopencv-imgproc406t64
      - libopencv-imgcodecs406t64
      - libopencv-core406t64
      - libtbb12
  opencl:
    # Includes all the compute runtime and OpenCL bits needed for Intel GPU support
    plugin: nil
    build-packages:
      - wget
    override-build: |
      if [ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]; then
        mkdir -p neo
        cd neo
        # Install Intel graphics compiler and compute runtime
        # This is required to enable GPU support for OpenVINO
        # https://docs.openvino.ai/2024/get-started/configurations/configurations-intel-gpu.html
        intel_graphics_compiler_version="2.5.6"
        intel_graphics_compiler_build="18417"
        compute_runtime_version="24.52.32224.5"
        wget https://github.com/intel/intel-graphics-compiler/releases/download/v${intel_graphics_compiler_version}/intel-igc-core-2_${intel_graphics_compiler_version}+${intel_graphics_compiler_build}_amd64.deb
        wget https://github.com/intel/intel-graphics-compiler/releases/download/v${intel_graphics_compiler_version}/intel-igc-opencl-2_${intel_graphics_compiler_version}+${intel_graphics_compiler_build}_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/${compute_runtime_version}/intel-level-zero-gpu_1.6.32224.5_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/${compute_runtime_version}/intel-opencl-icd_${compute_runtime_version}_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/${compute_runtime_version}/libigdgmm12_22.5.5_amd64.deb
        dpkg --root=$CRAFT_PART_INSTALL --force-all -i *.deb
        # update paths to the Intel Installable Client Drivers (ICDs) for OpenCL
        intel_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel.icd
        intel_icd_so_path=$(cat ${intel_icd})
        base_path="/snap/${SNAPCRAFT_PROJECT_NAME}/current"
        echo "${base_path}""${intel_icd_so_path}" > "${intel_icd}"
        intel_legacy1_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel_legacy1.icd
        if [ -f ${intel_legacy1_icd} ]; then
          intel_legacy1_icd_so_path=$(cat ${intel_legacy1_icd})
          echo "${base_path}""${intel_legacy1_icd_so_path}" > "${intel_legacy1_icd}"
        fi
        # fix broken sym links
        cd "${CRAFT_PART_INSTALL}"
        ln -sf "${base_path}"/usr/bin/ocloc-24.39.1 etc/alternatives/ocloc
        ln -sf "${base_path}"/etc/alternatives/ocloc usr/bin/ocloc
        craftctl default
      fi

  intel-graphics:
    plugin: nil
    stage-packages:
      - vainfo
      - intel-media-va-driver-non-free
      - libvpl2
      - libvpl-dev
      - libva-drm2
      - libva-glx2
      - libva-wayland2
      - libva-x11-2
      - libva-dev
      - libmfx1
      - libmfx-gen1
      - libmfx-gen-dev
      - libigdgmm12
      - libigdgmm-dev

apps:
  obs-studio:
    command: obs-wrapper
    extensions: [gnome]
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins/platforms
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/obs-plugins:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/obs-scripting:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/npu-libs:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
      LIBVA_DRIVERS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$LIBVA_DRIVERS_PATH
      OBS_PLUGINS_PATH: $SNAP/../components/$SNAP_REVISION/openvino-plugins
      OBS_PLUGINS_DATA_PATH: $SNAP/../components/$SNAP_REVISION/openvino-plugins
      OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - avahi-control
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - hardware-observe
      - jack1
      - joystick
      - kernel-module-observe
      - network
      - network-bind
      - opengl
      - password-manager-service
      - process-control
      - pulseaudio
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - screencast-legacy
      - system-observe
      - unity7
      - upower-observe
      - wayland
      - x11
      - intel-npu
      - npu-libs
