name: obs-studio
summary: Live streaming and video recording software
description: Free and open source software for video capturing, recording, and live
  streaming.
version: "30.0.0"
base: core22
grade: stable
confinement: strict
license: GPL-2.0
architectures:
  - build-on: amd64
compression: lzo

# Takes too long to lint during build
lint:
  ignore:
    - classic 
    - library

layout:
  /usr/lib/libndi.so.5:
    symlink: $SNAP/usr/lib/libndi.so.5

parts:
  ndi:
    plugin: dump
    source: https://github.com/obs-ndi/obs-ndi/releases/download/4.11.1/libndi5_5.5.3-1_amd64.deb
    source-type: deb
  launcher:
    plugin: dump
    source: snap/local
  obs:
    plugin: dump
    source: https://github.com/wimpysworld/obs-studio-portable/releases/download/r23316/obs-portable-30.0.0-r23316-ubuntu-22.04.tar.bz2
    stage-packages:
      - lib32gcc-s1 
      - lib32stdc++6 
      - libaom3 
      - libapparmor1 
      - libasound2 
      - libass9 
      - libasyncns0 
      - libatk-bridge2.0-0 
      - libatk1.0-0 
      - libatlas3-base 
      - libatspi2.0-0 
      - libavahi-client3 
      - libavahi-common3 
      - libavc1394-0 
      - libavcodec58 
      - libavdevice58 
      - libavfilter7 
      - libavformat58 
      - libavutil56 
      - libb2-1 
      - libblas3 
      - libblkid1 
      - libbluray2 
      - libbrotli1 
      - libbs2b0 
      - libbsd0 
      - libbz2-1.0 
      - libc6 
      - libcaca0 
      - libcairo-gobject2 
      - libcairo2 
      - libcap2 
      - libcdio-cdda2 
      - libcdio-paranoia2 
      - libcdio19 
      - libchromaprint1 
      - libcodec2-1.0 
      - libcom-err2 
      - libcups2 
      - libcurl4 
      - libdatrie1 
      - libdav1d5 
      - libdb5.3 
      - libdbus-1-3 
      - libdc1394-25 
      - libdecor-0-0 
      - libdouble-conversion3 
      - libdrm2 
      - libdw1 
      - libegl1 
      - libelf1 
      - libexpat1 
      - libfdk-aac2 
      - libffi8 
      - libfftw3-single3 
      - libflac8 
      - libflite1 
      - libfontconfig1 
      - libfreetype6 
      - libfribidi0 
      - libgbm1 
      - libgcc-s1 
      - libgcrypt20 
      - libgdk-pixbuf-2.0-0 
      - libgfortran5 
      - libgl1 
      - libglib2.0-0 
      - libglvnd0 
      - libglx0 
      - libgme0 
      - libgmp10 
      - libgnutls30 
      - libgomp1 
      - libgpg-error0 
      - libgraphite2-3 
      - libgsm1 
      - libgssapi-krb5-2 
      - libgstreamer-plugins-base1.0-0 
      - libgstreamer1.0-0 
      - libharfbuzz0b 
      - libhogweed6 
      - libicu70 
      - libidn2-0 
      - libiec61883-0 
      - libjack-jackd2-0 
      - libjansson4 
      - libjpeg-turbo8 
      - libk5crypto3 
      - libkeyutils1 
      - libkrb5-3 
      - libkrb5support0 
      - liblapack3 
      - libldap-2.5-0 
      - liblilv-0-0 
      - libluajit-5.1-2 
      - liblz4-1 
      - liblzma5 
      - libmbedcrypto7 
      - libmbedtls14 
      - libmbedx509-1 
      - libmd0 
      - libmd4c0 
      - libmfx1 
      - libmount1 
      - libmp3lame0 
      - libmpg123-0 
      - libmysofa1 
      - libncursesw6 
      - libnettle8 
      - libnghttp2-14 
      - libnorm1 
      - libnspr4 
      - libnss3 
      - libnuma1 
      - libogg0 
      - libopenal1 
      - libopenblas0-pthread 
      - libopencv-calib3d4.5d 
      - libopencv-core4.5d 
      - libopencv-dnn4.5d 
      - libopencv-features2d4.5d 
      - libopencv-flann4.5d 
      - libopencv-imgproc4.5d 
      - libopencv-objdetect4.5d 
      - libopengl0 
      - libopenjp2-7 
      - libopenmpt0 
      - libopus0 
      - liborc-0.4-0 
      - libp11-kit0 
      - libpango-1.0-0 
      - libpangocairo-1.0-0 
      - libpangoft2-1.0-0 
      - libpci3 
      - libpcre2-16-0 
      - libpcre2-8-0 
      - libpcre3 
      - libpgm-5.3-0 
      - libpipewire-0.3-0 
      - libpixman-1-0 
      - libpng16-16 
      - libpocketsphinx3 
      - libpostproc55 
      - libprocps8 
      - libprotobuf23 
      - libproxy1v5 
      - libpsl5 
      - libpugixml1v5 
      - libpulse0 
      - libpython3.10 
      - libqt6core6 
      - libqt6dbus6 
      - libqt6gui6 
      - libqt6network6 
      - libqt6svg6 
      - libqt6widgets6 
      - libqt6xml6 
      - libquadmath0 
      - librabbitmq4 
      - libraw1394-11 
      - librsvg2-2 
      - librtmp1 
      - librubberband2 
      - libsamplerate0 
      - libsasl2-2 
      - libsdl2-2.0-0 
      - libselinux1 
      - libserd-0-0 
      - libshine3 
      - libslang2 
      - libsnappy1v5 
      - libsndfile1 
      - libsndio7.0 
      - libsodium23 
      - libsord-0-0 
      - libsoxr0 
      - libspeex1 
      - libspeexdsp1 
      - libsphinxbase3 
      - libsratom-0-0 
      - libsrt1.4-gnutls 
      - libssh-4 
      - libssh-gcrypt-4 
      - libssl3 
      - libstdc++6 
      - libswresample3 
      - libswscale5 
      - libsystemd0 
      - libtasn1-6 
      - libtbb2 
      - libthai0 
      - libtheora0 
      - libtinfo6 
      - libtwolame0 
      - libudev1 
      - libudfread0 
      - libunistring2 
      - libunwind8 
      - libusb-1.0-0 
      - libuuid1 
      - libv4l-0 
      - libv4lconvert0 
      - libva-drm2 
      - libva-x11-2 
      - libva2 
      - libvdpau1 
      - libvidstab1.1 
      - libvorbis0a 
      - libvorbisenc2 
      - libvorbisfile3 
      - libvpx7 
      - libwayland-client0 
      - libwayland-cursor0 
      - libwayland-egl1 
      - libwayland-server0 
      - libwebp7 
      - libwebpmux3 
      - libx11-6 
      - libx11-xcb1 
      - libx264-163 
      - libx265-199 
      - libxau6 
      - libxcb-composite0 
      - libxcb-randr0 
      - libxcb-render0 
      - libxcb-shape0 
      - libxcb-shm0 
      - libxcb-xfixes0 
      - libxcb-xinerama0 
      - libxcb1 
      - libxcomposite1 
      - libxcursor1 
      - libxdamage1 
      - libxdmcp6 
      - libxext6 
      - libxfixes3 
      - libxi6 
      - libxinerama1 
      - libxkbcommon0 
      - libxml2 
      - libxrandr2 
      - libxrender1 
      - libxss1 
      - libxv1 
      - libxvidcore4 
      - libxxf86vm1 
      - libzimg2 
      - libzmq5 
      - libzstd1 
      - libzvbi0 
      - ocl-icd-libopencl1 
      - zlib1g 
      - qt6-image-formats-plugins 
      - qt6-qpa-plugins 
      - qt6-wayland 
      - gstreamer1.0-plugins-good 
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-x 
      - libgles2-mesa 
      - libvlc5 
      - vlc-plugin-base 
      - stterm
  cleanup:
    after: [obs,ndi,launcher]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
      set -eux
      cd /snap/gnome-42-2204/current
      find . -type f,l -exec rm -f $CRAFT_PRIME/{} \;
apps:
  obs-studio:
    common-id: com.obsproject.Studio
    extensions: [ gnome ]
    command: obs-wrapper
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt6/plugins:$QT_PLUGIN_PATH
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/openblas-pthread:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/bin/64bit:$SNAP/obs-plugins/64bit:$SNAP/data/obs-scripting/64bit:$SNAP/cef:$SNAP/lib
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - avahi-control
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - hardware-observe
      - jack1
      - joystick
      - kernel-module-observe
      - network
      - network-bind
      - opengl
      - password-manager-service
      - process-control
      - pulseaudio
      - raw-usb
      - removable-media
      - screen-inhibit-control
      - screencast-legacy
      - system-observe
      - unity7
      - upower-observe
      - wayland
      - x11
